# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkproj < Formula
  desc "A simple CLI tool to create project directories."
  homepage "https://github.com/jobehi/mkproj"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jobehi/mkproj/releases/download/v0.3.0/mkproj_Darwin_x86_64.tar.gz"
      sha256 "ed9d16e13fd81c9d47648865716552f075912fc803097ff85d58799e2344cad8"

      def install
        bin.install "mkproj"
      end
    end
    on_arm do
      url "https://github.com/jobehi/mkproj/releases/download/v0.3.0/mkproj_Darwin_arm64.tar.gz"
      sha256 "bc1a76b2386ec7352df24d54aa53b670a00f7b447eb886d6841ce8fd9aa1c3f2"

      def install
        bin.install "mkproj"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jobehi/mkproj/releases/download/v0.3.0/mkproj_Linux_x86_64.tar.gz"
        sha256 "e47a06dc97e0d7c88c21a19f1cbd618fc7bd0ba9038ee069cf2925f39d6bcd9c"

        def install
          bin.install "mkproj"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jobehi/mkproj/releases/download/v0.3.0/mkproj_Linux_arm64.tar.gz"
        sha256 "92948c56d9e9834d8ee50bc71a526c5cadf302ef8c8a109ad70fccc1594f7f47"

        def install
          bin.install "mkproj"
        end
      end
    end
  end
end
